# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('paterno', models.CharField(max_length=128)),
                ('materno', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=22, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('archivo', models.FileField(upload_to='pagos/')),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
                ('genero', models.CharField(choices=[('1', 'F'), ('2', 'M')], max_length=1)),
                ('confirmacion', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='asistente',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Status'),
        ),
    ]
