# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cveAs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Asistente')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('paterno', models.CharField(max_length=128)),
                ('materno', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=22, null=True)),
                ('institucion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha', models.DateTimeField()),
                ('cupo', models.IntegerField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cveTut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Tutorial'),
        ),
    ]
