# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20161207_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userio',
            fields=[
                ('aidi', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passw', models.CharField(max_length=30)),
            ],
        ),
    ]
