# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_userio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistente',
            name='status',
        ),
    ]
