# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_asistente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_crea', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_aut', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='imgs/')),
                ('mensaje', models.CharField(blank=True, max_length=150)),
                ('prioridad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='cveAs',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='cveTut',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='instructor',
        ),
        migrations.AddField(
            model_name='userio',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Asistente',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='anunc',
            name='autorizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aut', to='usuarios.Userio'),
        ),
        migrations.AddField(
            model_name='anunc',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crea', to='usuarios.Userio'),
        ),
    ]
