# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20170109_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userio',
            name='tipo',
            field=models.CharField(choices=[('ad', 'Administrador'), ('re', 'Regular')], default='re', max_length=2),
        ),
    ]
