# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20170109_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anunc',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='anunc',
            name='fecha_inicio',
        ),
    ]
