# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20170115_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunc',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anunc',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
