# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20170115_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='fecha_aut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_crea',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
