# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20170115_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='fecha_aut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_crea',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
