# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20170116_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='estado',
            field=models.CharField(choices=[('pe', 'Pendiente'), ('ap', 'Aprobado'), ('ne', 'Negado'), ('ex', 'Expirado')], default='pe', max_length=2),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='prioridad',
            field=models.CharField(choices=[('mb', 'Muy Baja'), ('ba', 'Baja'), ('me', 'Media'), ('al', 'Alta'), ('ma', 'Muy Alta')], default='me', max_length=2),
        ),
    ]
