# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20170128_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunc',
            name='urli',
            field=models.URLField(null=True),
        ),
    ]
