# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_anunc_urli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='urli',
            field=models.URLField(blank=True, null=True),
        ),
    ]
