# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20170206_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='prioridad',
            field=models.CharField(choices=[('nn', 'Muy Baja'), ('ni', 'Baja'), ('me', 'Media'), ('al', 'Alta'), ('aa', 'Muy Alta')], default='me', max_length=2),
        ),
    ]
