# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 17:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20170228_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='fecha_fin',
            field=models.DateField(default=usuarios.models.fin_default),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
