# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20170322_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunc',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anunc',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
