# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20170322_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userio',
            name='correo',
            field=models.EmailField(default='dummy@dummy.com', max_length=254),
        ),
    ]
