# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_userio_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userio',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
